#!/usr/bin/env python

import os;
import getpass;
import subprocess;
from time import gmtime, strftime;

print "---------------\nCreating MySQL databases"
username  = str(raw_input("  Enter MySQL username: "));
password  = getpass.getpass("  Enter MySQL password: ");
dbpath    = "../../database"
dbbakpath = "../../database/backup"

# Check the database access before continuing

# There is probably a more correct way to see if the username/password are valid, but this works
with open(os.devnull,"w") as fnull:
  cmd = "mysql -u %s --password=%s -e 'SHOW DATABASES'" % (username, password);
  ret = subprocess.call(cmd, shell = True, stdout = fnull, stderr = fnull);
  if(ret) :
    print "Invalid username or password";
    exit(1);

print "\n\n";

# Backup the current databases and load the blank new ones
with open(os.devnull,"w") as fnull:
  print "  Creating backup directory:\n    %s" % (dbbakpath);

  cmd = "mkdir %s" % (dbbakpath);
  ret = subprocess.call(cmd, shell = True, stdout = fnull, stderr = fnull);
  print "  Creating backup databases:";

  backup = strftime("%Y%m%d_%H%M%S", gmtime()) + "_OAData.sql";
  print "    %s" % (backup);
  cmd = "mysqldump -u %s --password=%s OAData > %s/%s" % (username, password, dbbakpath, backup);
  ret = subprocess.call(cmd, shell = True, stdout = fnull, stderr = fnull);

  backup = strftime("%Y%m%d_%H%M%S", gmtime()) + "_OAServer.sql";
  print "    %s" % (backup);
  cmd = "mysqldump -u %s --password=%s OAServer > %s/%s" % (username, password, dbbakpath, backup);
  ret = subprocess.call(cmd, shell = True, stdout = fnull, stderr = fnull);

  print "  Creating OpenAquaponics databases:";

  print "    OAServer" % ();
  cmd = "mysql -u %s --password=%s -e 'DROP DATABASE IF EXIST OAServer; CREATE DATABASE OAServer'" % (username, password);
  ret = subprocess.call(cmd, shell = True, stdout = fnull, stderr = fnull);
  cmd = "mysql -u %s --password=%s OAServer < %s/OAServer.sql" % (username, password, dbpath);
  ret = subprocess.call(cmd, shell = True, stdout = fnull, stderr = fnull);

  print "    OAData" % ();

  cmd = "mysql -u %s --password=%s -e 'DROP DATABASE IF EXISTS OAData; CREATE DATABASE OAData'" % (username, password);
  ret = subprocess.call(cmd, shell = True, stdout = fnull, stderr = fnull);


print "\n\n"
