#!/usr/bin/env python

import os;
import getpass;
import subprocess;
import argparse;
import random;


def main(**kwargs):

  # Process the command line arguements
  if(kwargs['u']): username = kwargs['u'];
  else: username  = str(raw_input("  Enter MySQL username: "));

  if(kwargs['p']): password = kwargs['p'];
  else: password  = getpass.getpass("  Enter MySQL password: ");
  

  # There is probably a more correct way to see if the username/password are valid, but this works
  with open(os.devnull,"w") as fnull:
    cmd = "mysql -u %s --password=%s -e 'SHOW DATABASES'" % (username, password);
    ret = subprocess.call(cmd, shell = True, stdout = fnull);
    if(ret) :
      exit(1);

  print "---------------\nCreating new OASystem"

  OASystemCfg = {};
  OASystemCfg["sUsername"]    = str(raw_input("  Enter Username    (REQUIRED): "));
  OASystemCfg["sDescription"] = str(raw_input("  Enter Description (OPTIONAL): "));
  OASystemCfg["sSystemId"]    = str("%X" % (random.randrange(0, 0xFFFFFFFF)));
  OASystemCfg["sGroupId"]     = str("");
  OASystemCfg["bPublic"]      = str("1"); # Make this a validated input
  OASystemCfg["bEnable"]      = str("1"); # Make this a validated input

  key_str = '';
  val_str = '';
  for key, val in OASystemCfg.iteritems():
    if(len(val) > 0):
      key_str = key_str + key + ',';
      val_str = val_str + '"' + val + '",';
    else :
      key_str = key_str + key + ',';
      val_str = val_str + 'NULL,';

  key_str = key_str[:-1];
  val_str = val_str[:-1];

  print "  -- Attempting to create OASystem: %s --" % (OASystemCfg["sSystemId"]);

  with open(os.devnull,"w") as fnull:
    cmd = "mysql -u %s --password=%s -e 'INSERT INTO OAServer.OASystemCfg (%s) VALUES (%s)'" % (username, password, key_str, val_str);
    ret = subprocess.call(cmd, shell = True, stdout = fnull);


if __name__ == "__main__":
  parser = argparse.ArgumentParser(description = "Create a user in the database", version = "%(prog)s 1.0");
  parser.add_argument('-u', nargs="?", type = str, default = "", help = "MySQL database username");
  parser.add_argument('-p', nargs="?", type = str, default = "", help = "MySQL database password");
  args = parser.parse_args();
  main(**vars(args));




