#!/usr/bin/env python

import os;
import getpass;
import subprocess;
from time import gmtime, strftime;

print "---------------\nLoad MySQL database with sample data"
print "NOTE: You may need to run ./create_database if this fails";
username  = str(raw_input("  Enter MySQL username: "));
password  = getpass.getpass("  Enter MySQL password: ");
dbpath    = "../../database"

# There is probably a more correct way to see if the username/password are valid, but this works
with open(os.devnull,"w") as fnull:
  cmd = "mysql -u %s --password=%s -e 'SHOW DATABASES'" % (username, password);
  ret = subprocess.call(cmd, shell = True, stdout = fnull, stderr = fnull);
  if(ret) :
    print "Invalid username or password";
    exit(1);

print "";

# Backup the current databases and load the blank new ones
with open(os.devnull,"w") as fnull:
  print "  Loading Sample data:" %();

  print "    OAServer" % ();
  cmd = "mysql -u %s --password=%s OAServer < %s/Sample_OAServer.sql" % (username, password, dbpath);
  ret = subprocess.call(cmd, shell = True, stdout = fnull, stderr = fnull);

  print "    OAData" % ();
  cmd = "mysql -u %s --password=%s OAData < %s/Sample_OAData.sql" % (username, password, dbpath);
  ret = subprocess.call(cmd, shell = True, stdout = fnull, stderr = fnull);


print ""
